import type {
  BadgeDefinition,
  CryptoCoinId,
  Conversation,
  Message,
  NotificationItem,
  Post,
  ShopItem,
  TriviaQuestion,
  UserProfile,
} from "@/types/models";

export const badges: BadgeDefinition[] = [
  { id: "first-post", type: "send-messages", name: "First Post", description: "Published your first pulse.", rarity: "common", icon: "Sparkles", baseRequirement: 100, requirementStep: 100, rewardXp: 10, rewardGems: 5 },
  { id: "starter", type: "followers", name: "Getting Started", description: "Finished onboarding and polished your profile.", rarity: "uncommon", icon: "Compass", baseRequirement: 5, requirementStep: 5, rewardXp: 10, rewardGems: 5 },
  { id: "level-5", type: "day-streak", name: "Level 5", description: "Reached level five in the network.", rarity: "rare", icon: "Trophy", baseRequirement: 7, requirementStep: 7, rewardXp: 10, rewardGems: 5 },
];

export const users: UserProfile[] = [
  {
    uid: "demo-user",
    email: "demo@pulsearc.app",
    displayName: "Nova Vale",
    handle: "novavale",
    photoURL: null,
    photoStoragePath: null,
    bannerURL: null,
    bannerStoragePath: null,
    bannerColor: "linear-gradient(135deg, #ff6b57 0%, #ffb36b 100%)",
    bio: "Designing playful systems for digital communities.",
    website: "https://pulsearc.demo",
    location: "Brisbane",
    interests: ["design", "games", "community"],
    level: 6,
    xp: 820,
    credits: 1640,
    featuredBadgeId: "level-5",
    ownedBadgeIds: ["first-post", "starter", "level-5"],
    badgeProgress: {
      "first-post": { badgeId: "first-post", level: 1, progress: 42, unlockedAt: "2026-03-01T08:00:00.000Z" },
      starter: { badgeId: "starter", level: 1, progress: 3, unlockedAt: "2026-02-18T08:00:00.000Z" },
      "level-5": { badgeId: "level-5", level: 1, progress: 5, unlockedAt: "2026-04-21T08:00:00.000Z" },
    },
    isPremium: true,
    isPremiumPlus: false,
    isModerator: true,
    isVerified: true,
    isPrivate: false,
    onboardingComplete: true,
    theme: "graphite",
    accentColor: "#ff6b57",
    gems: 84,
    coinHoldings: {
      wutax: 13.46,
      galaxy: 3.36,
      arc: 5.95,
      nebula: 3.66,
      spark: 5.77,
      lumen: 0,
      titan: 0,
    } satisfies Record<CryptoCoinId, number>,
    coinInvestmentTotals: {
      wutax: 12,
      galaxy: 7.8,
      arc: 4.1,
      nebula: 5.2,
      spark: 2.4,
      lumen: 0,
      titan: 0,
    } satisfies Record<CryptoCoinId, number>,
    casinoCoins: 3,
    gamblingGains: 240,
    gamblingLosses: 175,
    ownedNameColorIds: ["default", "ember", "mint", "flux", "auroraShift"],
    ownedThemeIds: ["graphite", "mist", "aurora", "emberDusk"],
    equippedNameColorId: "auroraShift",
    ownedProfileBorderIds: ["border-none", "solid-coral", "gradient-sunset", "animated-prism"],
    equippedProfileBorderId: "animated-prism",
    followerCount: 382,
    followingCount: 111,
    postCount: 46,
    rottenTomatoCount: 2,
    badgeCount: 3,
    joinedAt: "2026-01-11T10:00:00.000Z",
    lastOnlineAt: "2026-08-03T08:42:00.000Z",
  },
  {
    uid: "mira",
    email: "mira@example.com",
    displayName: "Mira Rune",
    handle: "mirarune",
    photoURL: null,
    photoStoragePath: null,
    bannerURL: null,
    bannerStoragePath: null,
    bannerColor: "linear-gradient(135deg, #1f9d8b 0%, #8df0c8 100%)",
    bio: "Building tiny rituals into apps.",
    website: "",
    location: "Melbourne",
    interests: ["ux", "wellbeing"],
    level: 4,
    xp: 465,
    credits: 890,
    featuredBadgeId: "starter",
    ownedBadgeIds: ["starter"],
    badgeProgress: {
      starter: { badgeId: "starter", level: 1, progress: 1, unlockedAt: "2026-04-10T08:00:00.000Z" },
    },
    isPremium: false,
    isPremiumPlus: false,
    isModerator: false,
    isVerified: false,
    isPrivate: false,
    onboardingComplete: true,
    theme: "mist",
    accentColor: "#1f9d8b",
    gems: 27,
    coinHoldings: {
      wutax: 2.88,
      galaxy: 0.42,
      arc: 4.76,
      nebula: 1.22,
      spark: 1.92,
      lumen: 0,
      titan: 0,
    } satisfies Record<CryptoCoinId, number>,
    coinInvestmentTotals: {
      wutax: 2.5,
      galaxy: 0.8,
      arc: 3.2,
      nebula: 1.4,
      spark: 0.9,
      lumen: 0,
      titan: 0,
    } satisfies Record<CryptoCoinId, number>,
    casinoCoins: 1,
    gamblingGains: 60,
    gamblingLosses: 95,
    ownedNameColorIds: ["default"],
    ownedThemeIds: ["graphite", "mist"],
    equippedNameColorId: "default",
    ownedProfileBorderIds: ["border-none"],
    equippedProfileBorderId: "border-none",
    followerCount: 124,
    followingCount: 79,
    postCount: 18,
    rottenTomatoCount: 1,
    badgeCount: 1,
    joinedAt: "2026-02-16T10:00:00.000Z",
    lastOnlineAt: "2026-08-02T22:10:00.000Z",
  },
];

export const posts: Post[] = [
  {
    id: "post-1",
    authorId: "demo-user",
    content: "PulseArc daily challenge idea: reward thoughtful replies more than raw volume. Healthier conversations, better signals.",
    imageURL: null,
    imageStoragePath: null,
    gifURL: null,
    parentPostId: null,
    repostedPostId: null,
    quotedPostId: null,
    reactionCount: 42,
    replyCount: 8,
    repostCount: 5,
    bookmarkCount: 14,
    averageRating: 4.4,
    starRatingCount: 12,
    rottenTomatoCount: 0,
    tags: ["product", "community"],
    visibility: "public",
    createdAt: "2026-07-15T07:12:00.000Z",
  },
  {
    id: "post-2",
    authorId: "mira",
    content: "Today's arcade trivia streak is keeping my coffee breaks dangerously competitive.",
    imageURL: null,
    imageStoragePath: null,
    gifURL: null,
    parentPostId: null,
    repostedPostId: null,
    quotedPostId: null,
    reactionCount: 19,
    replyCount: 2,
    repostCount: 1,
    bookmarkCount: 4,
    averageRating: 3.8,
    starRatingCount: 6,
    rottenTomatoCount: 1,
    tags: ["arcade", "streaks"],
    visibility: "public",
    createdAt: "2026-07-15T04:05:00.000Z",
  },
];

export const notifications: NotificationItem[] = [
  { id: "n1", type: "badge", title: "Badge unlocked", body: "You earned Level 5.", createdAt: "2026-07-15T06:55:00.000Z", read: false },
  { id: "n2", type: "reaction", title: "New reactions", body: "Mira and 6 others reacted to your post.", createdAt: "2026-07-15T05:20:00.000Z", read: false },
  { id: "n3", type: "reward", title: "Daily reward", body: "You claimed 25 credits from arcade trivia.", createdAt: "2026-07-14T23:00:00.000Z", read: true },
];

export const conversations: Conversation[] = [
  {
    id: "conv-1",
    participantIds: ["demo-user", "mira"],
    title: "Mira Rune",
    unreadCount: 2,
    lastMessage: "Let's ship the badge animations tonight.",
    updatedAt: "2026-07-15T07:10:00.000Z",
  },
];

export const messages: Message[] = [
  { id: "m1", conversationId: "conv-1", senderId: "mira", body: "Do we keep OLED mode in the demo build?", createdAt: "2026-07-15T07:00:00.000Z" },
  { id: "m2", conversationId: "conv-1", senderId: "demo-user", body: "Yes. It makes the accent color system feel much stronger.", createdAt: "2026-07-15T07:05:00.000Z" },
];

export const shopItems: ShopItem[] = [
  { id: "shop-1", name: "Solar Frame", category: "Avatar Frame", rarity: "rare", price: 340, description: "A warm flare ring for standout profiles." },
  { id: "shop-2", name: "Midnight Grid", category: "Profile Theme", rarity: "epic", price: 520, description: "A sharp editorial theme with subtle grid texture." },
];

export const triviaQuestions: TriviaQuestion[] = [
  {
    id: "q1",
    prompt: "Which reward should remain earned instead of sold in this demo?",
    choices: ["Credits", "Achievement badges", "Themes", "Reaction packs"],
    answer: "Achievement badges",
  },
];
