export const COLLECTIONS = {
  users: "users",
  markets: "markets",
  posts: "posts",
  reactions: "reactions",
  follows: "follows",
  bookmarks: "bookmarks",
  notifications: "notifications",
  conversations: "conversations",
  messages: "messages",
  badges: "badges",
  userBadges: "userBadges",
  xpTransactions: "xpTransactions",
  activityHistory: "activityHistory",
  postViews: "postViews",
} as const;
